version: "3.8"

services:
  postgres:
    image: postgres:13
    container_name: ans_postgres
    environment:
      POSTGRES_USER: ans_admin
      POSTGRES_PASSWORD: ans_password
      POSTGRES_DB: ans_db
    volumes:
      - local_pgdata:/var/lib/postgresql/data
      - ./database/data:/dados  
      - ./database/scripts:/scripts 
    ports:
      - "5432:5432"
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: ans_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@ans.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
  
volumes:
  local_pgdata:
  pgadmin_data: